var SessionConstants = {
  RECEIVED_ERRORS: "RECEIVED_ERRORS",
  RECEIVED_CURRENT_USER: "RECEIVED_CURRENT_USER",
  RECEIVED_SESSION_TOKEN: "RECEIVED_SESSION_TOKEN"
};

module.exports = SessionConstants;
