# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f5b5df142eab51312ef11fc6fc6bb9acdabd4c889939378abbfb44060cf94183cda12249fc8b0389ce8b0889fb7e47c8f2ac878d2615829596be961de44be6

test:
  secret_key_base: 966e313da4d3a75379077f1d5496d8a8c50052ede97f1ade6803cfef8f4a30421ffad9ccb2ae181bb00eef26bee33d1570b95aa81af889b7256ea3d9f664bc4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
